Repository rjcncpt/StarCitizen-Deutsch-INI, pull requests merged in 2024-03, with the labels that each got.

#496 Update Festlegungen.md
  docs_tools/Festlegungen.md
Labels: Dokumentation, Geprüft

#497 Test temporär deaktivieren
  .github/tests/key_test.py
Labels: Prüfbar, Automatisierung, Tools

#511 [de] aus dem Release Titel entfernt
  .github/workflows/create_realease.yml
Labels: Geprüft, Automatisierung
