Repository rjcncpt/StarCitizen-Deutsch-INI, pull requests merged in 2024-05, with the labels that each got.

#539 Create ZIP with Full Translation
  .github/workflows/create_realease.yml
Labels: Geprüft, Automatisierung, LIVE

#542 Fix full release workflow
  .github/workflows/create_realease.yml
Labels: Automatisierung

#545 Doku zu unserer Übersetzung
  docs_tools/doku/README.md
Labels: Geprüft

#549 PR Template hinzugefügt
  .github/pull_request_template.md
Labels: Geprüft, Tools
