Repository rjcncpt/StarCitizen-Deutsch-INI, pull requests merged in 2024-01, with the labels that each got.

#380 3.22.0 EPTU.9012505 | Neuer PTU Build
  en/ptu/3.22.0 EPTU.9012505.Build
  ptu/3.22.0 EPTU.9012505.Build
Labels: PTU, Update

#443 3.22.0A LIVE.9035564 | Auto-Format Anpassungen
  .github/tests/check_for_whitespace_before_comma.py
  .github/tests/encoding_test.py
  .github/tests/key_test.py
  .github/workflows/tests.yml
  README.md
  updater/readme.md
Labels: Dokumentation, Geprüft, Automatisierung

#452 Update README.md
  README.md
Labels: Update
